name: CI


on:
  

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
 
  build:
    
    runs-on: self-hosted

    
    steps:
      
      
      - uses: actions/checkout@v4


      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: 7c33877b-7aee-4e54-8e82-17c8957a84a5
          tenant-id: 1258b573-d88f-4e74-84ce-f1cbf374c8f1
          subscription-id: 4e5f32a3-4367-471e-8772-b7424c3fd9d0
          client-secret: vc28Q~.rguZufrZBM.aAAQnFHt~ioFS31W87Lcpy
